# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(500, 500)
        self.nameLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.nameLabel.setGeometry(QtCore.QRect(30, 30, 180, 30))
        self.nameLabel.setObjectName("nameLabel")
        self.nameEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.nameEdit.setGeometry(QtCore.QRect(220, 30, 240, 30))
        self.nameEdit.setObjectName("nameEdit")
        self.roastingLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.roastingLabel.setGeometry(QtCore.QRect(30, 80, 180, 30))
        self.roastingLabel.setObjectName("roastingLabel")
        self.roastingComboBox = QtWidgets.QComboBox(AddEditCoffeeForm)
        self.roastingComboBox.setGeometry(QtCore.QRect(220, 80, 240, 30))
        self.roastingComboBox.setObjectName("roastingComboBox")
        self.typeLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.typeLabel.setGeometry(QtCore.QRect(30, 130, 180, 30))
        self.typeLabel.setObjectName("typeLabel")
        self.typeComboBox = QtWidgets.QComboBox(AddEditCoffeeForm)
        self.typeComboBox.setGeometry(QtCore.QRect(220, 130, 240, 30))
        self.typeComboBox.setObjectName("typeComboBox")
        self.tasteLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.tasteLabel.setGeometry(QtCore.QRect(30, 180, 180, 30))
        self.tasteLabel.setObjectName("tasteLabel")
        self.tasteEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.tasteEdit.setGeometry(QtCore.QRect(220, 180, 240, 30))
        self.tasteEdit.setObjectName("tasteEdit")
        self.priceLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.priceLabel.setGeometry(QtCore.QRect(30, 230, 180, 30))
        self.priceLabel.setObjectName("priceLabel")
        self.priceSpinBox = QtWidgets.QDoubleSpinBox(AddEditCoffeeForm)
        self.priceSpinBox.setGeometry(QtCore.QRect(220, 230, 240, 30))
        self.priceSpinBox.setMaximum(1000000.0)
        self.priceSpinBox.setProperty("value", 0.0)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.volumeLabel = QtWidgets.QLabel(AddEditCoffeeForm)
        self.volumeLabel.setGeometry(QtCore.QRect(30, 280, 180, 30))
        self.volumeLabel.setObjectName("volumeLabel")
        self.volumeSpinBox = QtWidgets.QSpinBox(AddEditCoffeeForm)
        self.volumeSpinBox.setGeometry(QtCore.QRect(220, 280, 240, 30))
        self.volumeSpinBox.setMaximum(100000)
        self.volumeSpinBox.setObjectName("volumeSpinBox")
        self.saveButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.saveButton.setGeometry(QtCore.QRect(100, 360, 130, 40))
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.cancelButton.setGeometry(QtCore.QRect(270, 360, 130, 40))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Кофе"))
        self.nameLabel.setText(_translate("AddEditCoffeeForm", "Название сорта:"))
        self.roastingLabel.setText(_translate("AddEditCoffeeForm", "Степень обжарки:"))
        self.typeLabel.setText(_translate("AddEditCoffeeForm", "Молотый/в зернах:"))
        self.tasteLabel.setText(_translate("AddEditCoffeeForm", "Описание вкуса:"))
        self.priceLabel.setText(_translate("AddEditCoffeeForm", "Цена:"))
        self.volumeLabel.setText(_translate("AddEditCoffeeForm", "Объем упаковки:"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Отмена"))
